<ArcPad>
	<LAYER name="OWEB Project Area">
		
		<QUERY where=""/>
	<SYMBOLOGY><SIMPLELABELRENDERER visible="false" field="Acres"><TEXTSYMBOL font="Arial" charset="" fontsize="7.800000" fontstyle="regular" fontcolor="0,0,0" angle="0.000000"/></SIMPLELABELRENDERER><SIMPLERENDERER label=""><SIMPLEPOLYGONSYMBOL filltype="solid" filltransparency="0" fillcolor="255,255,255" boundarytype="solid" boundarywidth="3.000000" boundarycolor="0,0,0" boundarytransparency="1"/></SIMPLERENDERER></SYMBOLOGY></LAYER>
</ArcPad>
